server:
  port: 8081

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/demouserDB
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true